### ISSUE TITLE
init command still adds exclude section to config

### ISSUE THREAD

**Issue by juliushaertl** [ChristophWurst/krankerl#838]
After running `krankerl init` the exclude section is still added to the krankerl.toml file, which causes the follow up commands to fail:

```
$ krankerl init
krankerl.toml created.
$ cat krankerl.toml
[package]
exclude = [

]

before_cmds = [

]
$ krankerl package
Cloning app
App cloned to "/tmp/krankerl.nX8r60D7UUMn"
Dependency installation skipped
Building app
thread '<unnamed>' panicked at 'The exclude array in krankerl.toml was removed in 0.12. Use a .nextcloudignore instead.', src/config/app.rs:69:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/packaging/mod.rs:42:5
```

**Comment by ChristophWurst** [comment]
whoopsi

**Comment by icewind1991** [comment]
https://github.com/ChristophWurst/krankerl/pull/788 :eyes:
